version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
      - ./:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php:
    build:
      context: ./docker/php
    container_name: phpengine
    working_dir: /application
    volumes:
      - ./:/application

  mysql:
    image: mysql
    container_name: database
    env_file:
      - ./docker/mysql/database.env
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    container_name: mailer
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: queue
    env_file:
      - ./docker/rabbitmq/queue.env
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  data-volume: